site_name: Rui's Blog
site_url: https://mydomain.org/mysite
site_author: Rui Bo
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rus
plugins:
  - search
  - awesome-pages
sort: ascending
nav:
  - Home: index.md
  - About: about.md
  - Blog: blog/
  - Misc:   
      - mkdocs: misc/mkdocs.md
