site_name: Rui's Blog
site_url: https://mydomain.org/mysite

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - rus
nav:
  - Home: index.md
  - About: about.md
  - Blog:
      - Post1:{if there is}: blog/post1.md
      - Post2:{comments}: blog/post2.md  
  - Misc:   
      - mkdocs: misc/mkdocs.md
      - Unipy: misc/Unipy.md
